import { describe, it, expect, beforeEach, vi } from 'vitest'
import { handleSubtitlesCaptured, setLastVideoId, getLastVideoId } from './handlers'
import { Config } from './config'
import { store, SubtitleStore } from './store'
import { translationManager } from './ai/manager'
import { ProfileManager } from './profiles'

// Mock dependencies
vi.mock('./config', () => ({
  Config: {
    get: vi.fn()
  }
}))

vi.mock('./VideoController', () => ({
  videoController: {
    seekToNext: vi.fn(),
    seekToPrev: vi.fn(),
    replayCurrent: vi.fn()
  }
}))

vi.mock('./store', () => ({
  store: {
    clear: vi.fn(),
    setSourceLanguage: vi.fn(),
    setIsAutoGenerated: vi.fn(),
    replaceSegments: vi.fn(),
    addChangeListener: vi.fn()
  },
  SubtitleStore: {
    parseYouTubeJSON: vi.fn()
  }
}))

vi.mock('./ai/manager', () => ({
  translationManager: {
    reset: vi.fn()
  }
}))

vi.mock('./profiles', () => ({
  ProfileManager: {
    autoSelectProfileByLanguage: vi.fn(),
    getActiveProfile: vi.fn()
  }
}))

vi.mock('./logger', () => ({
  contentLogger: vi.fn()
}))

describe('handleSubtitlesCaptured', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    setLastVideoId(null)
    
    // Mock window.location
    const mockLocation = {
      hostname: 'www.youtube.com',
      search: '?v=video123'
    }
    vi.stubGlobal('location', mockLocation)
    
    // Default config
    vi.mocked(Config.get).mockResolvedValue({
      autoSelectProfile: true,
      autoGeneratedBatchSize: 10
    } as any)
    
    // Default SubtitleStore parse
    vi.mocked(SubtitleStore.parseYouTubeJSON).mockReturnValue({
      segments: [{ start: 0, end: 1000, text: 'Hello' }],
      isAutoGenerated: false
    })
  })

  it('should ignore messages if platform is not YouTube', async () => {
    vi.stubGlobal('location', { hostname: 'example.com', search: '' })
    
    await handleSubtitlesCaptured({ type: 'SI_SUBTITLES_CAPTURED', payload: {} })
    
    expect(translationManager.reset).not.toHaveBeenCalled()
  })

  it('should ignore messages if videoId doesn\'t match current video', async () => {
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload: {}, 
      videoId: 'different_video' 
    })
    
    expect(translationManager.reset).not.toHaveBeenCalled()
  })

  it('should reset state and replace segments on valid message', async () => {
    const payload = { test: 'data' }
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload, 
      videoId: 'video123',
      language: 'ja'
    })
    
    expect(store.clear).toHaveBeenCalled()
    expect(translationManager.reset).toHaveBeenCalled()
    expect(getLastVideoId()).toBe('video123')
    expect(store.setSourceLanguage).toHaveBeenCalledWith('ja')
    expect(store.replaceSegments).toHaveBeenCalledWith([{ start: 0, end: 1000, text: 'Hello' }])
  })

  it('should trigger profile auto-selection if enabled', async () => {
    vi.mocked(ProfileManager.autoSelectProfileByLanguage).mockResolvedValue(true)
    vi.mocked(ProfileManager.getActiveProfile).mockResolvedValue({ name: 'Japanese', id: 'ja' } as any)
    
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload: {}, 
      language: 'ja' 
    })
    
    expect(ProfileManager.autoSelectProfileByLanguage).toHaveBeenCalledWith('ja')
    expect(translationManager.reset).toHaveBeenCalled() // Reset happens after profile selection
  })

  it('should not trigger profile auto-selection if disabled', async () => {
    vi.mocked(Config.get).mockResolvedValue({
      autoSelectProfile: false
    } as any)
    
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload: {}, 
      language: 'ja' 
    })
    
    expect(ProfileManager.autoSelectProfileByLanguage).not.toHaveBeenCalled()
  })

  it('should handle messages without videoId (legacy or other platform)', async () => {
    // If message.videoId is missing, it skips the safety check and proceeds
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload: {}
    })
    
    expect(translationManager.reset).toHaveBeenCalled()
    expect(getLastVideoId()).toBe('video123')
  })

  it('should perform exactly one reset even if profile changes', async () => {
    vi.mocked(ProfileManager.autoSelectProfileByLanguage).mockResolvedValue(true)
    vi.mocked(ProfileManager.getActiveProfile).mockResolvedValue({ name: 'Japanese', id: 'ja' } as any)
    
    await handleSubtitlesCaptured({ 
      type: 'SI_SUBTITLES_CAPTURED', 
      payload: {}, 
      language: 'ja' 
    })
    
    expect(translationManager.reset).toHaveBeenCalledTimes(1)
    expect(store.clear).toHaveBeenCalledTimes(1)
  })
})
