import { Config } from './config'
import { videoController } from './VideoController'
import { store, SubtitleStore } from './store'
import { translationManager } from './ai/manager'
import { ProfileManager } from './profiles'
import { contentLogger } from './logger'
import { Platform } from './types'

export const detectPlatform = (): Platform => {
  const host = window.location.hostname
  if (host.includes('youtube.com')) return 'youtube'
  if (host.includes('stremio.com')) return 'stremio'
  return 'unknown'
}

export const handleCommand = async (command: string) => {
  const config = await Config.get()
  if (!config.isEnabled) return

  switch (command) {
    case 'next_segment':
      videoController.seekToNext()
      break
    case 'previous_segment':
      videoController.seekToPrev()
      break
    case 'replay_segment':
      videoController.replayCurrent()
      break
  }
}

export interface SubtitleCapturedMessage {
  type: 'SI_SUBTITLES_CAPTURED'
  payload: unknown
  videoId?: string
  language?: string
}

let lastVideoId: string | null = null
let isProcessingSubtitles = false

export const handleSubtitlesCaptured = async (message: SubtitleCapturedMessage) => {
  if (isProcessingSubtitles) {
    contentLogger('Already processing a subtitles message. Skipping concurrent call.')
    return
  }

  const platform = detectPlatform()
  if (platform !== 'youtube') return

  const currentVideoId = new URLSearchParams(window.location.search).get('v')

  // Safety check: ensure the message is for the current video
  if (message.videoId && message.videoId !== currentVideoId) {
    contentLogger(`Ignoring subtitles for different video (got ${message.videoId}, expected ${currentVideoId})`)
    return
  }

  isProcessingSubtitles = true

  try {
    const config = await Config.get()
    const { segments, isAutoGenerated } = SubtitleStore.parseYouTubeJSON(message.payload, config.autoGeneratedBatchSize)

    if (segments.length === 0) {
      contentLogger('No segments found in subtitles message. Ignoring payload.')
      return
    }

    contentLogger(`Processing ${segments.length} segments for video ${currentVideoId}:`, message)

    // 1. Handle profile change first so we initialize with correct settings
    if (message.language && config.autoSelectProfile) {
      try {
        const changed = await ProfileManager.autoSelectProfileByLanguage(message.language)
        if (changed) {
          const activeProfile = await ProfileManager.getActiveProfile()
          contentLogger(`Profile automatically changed to "${activeProfile.name}" (${activeProfile.id}) for language "${message.language}"`)
        }
      } catch (e) {
        contentLogger('ERROR: Profile auto-selection failed:', e)
      }
    }

    // 2. Perform ONE centralized hard reset for any change (new video, profile change, or just new track content)
    contentLogger(`Resetting AI state for video ${currentVideoId}.`)
    store.clear()
    await translationManager.reset()
    
    lastVideoId = currentVideoId
    
    if (message.language) {
      store.setSourceLanguage(message.language)
    }

    store.setIsAutoGenerated(isAutoGenerated)
    store.replaceSegments(segments)
    contentLogger('Subtitles successfully loaded into store.')
  } catch (e) {
    contentLogger('ERROR: Failed to handle captured subtitles:', e)
  } finally {
    isProcessingSubtitles = false
  }
}

// Exported for testing purposes
export const getLastVideoId = () => lastVideoId
export const setLastVideoId = (id: string | null) => { lastVideoId = id }
