import { Config } from './config'
import { videoController } from './VideoController'
import { store, SubtitleStore } from './store'
import { translationManager } from './ai/manager'
import { ProfileManager } from './profiles'
import { contentLogger } from './logger'
import { Platform } from './types'

export const detectPlatform = (): Platform => {
  const host = window.location.hostname
  if (host.includes('youtube.com')) return 'youtube'
  if (host.includes('stremio.com')) return 'stremio'
  return 'unknown'
}

export const handleCommand = async (command: string) => {
  const config = await Config.get()
  if (!config.isEnabled) return

  switch (command) {
    case 'next_segment':
      videoController.seekToNext()
      break
    case 'previous_segment':
      videoController.seekToPrev()
      break
    case 'replay_segment':
      videoController.replayCurrent()
      break
  }
}

export interface SubtitleCapturedMessage {
  type: 'SI_SUBTITLES_CAPTURED'
  payload: unknown
  videoId?: string
  language?: string
}

let lastVideoId: string | null = null

export const handleSubtitlesCaptured = async (message: SubtitleCapturedMessage) => {
  const platform = detectPlatform()
  if (platform !== 'youtube') return

  const currentVideoId = new URLSearchParams(window.location.search).get('v')

  // Safety check: ensure the message is for the current video
  if (message.videoId && message.videoId !== currentVideoId) {
    contentLogger(`Ignoring subtitles for different video (got ${message.videoId}, expected ${currentVideoId})`)
    return
  }

  contentLogger('Accepted subtitles message to process:', message)

  const config = await Config.get()

  // 1. Handle profile change first so we initialize with correct settings
  if (message.language && config.autoSelectProfile) {
    const changed = await ProfileManager.autoSelectProfileByLanguage(message.language)
    if (changed) {
      const activeProfile = await ProfileManager.getActiveProfile()
      contentLogger(`Profile automatically changed to "${activeProfile.name}" (${activeProfile.id}) for language "${message.language}"`)
    }
  }

  // 2. Perform ONE centralized hard reset for any change (new video, profile change, or just new track content)
  contentLogger(`Resetting state for video ${currentVideoId}.`)
  store.clear()
  await translationManager.reset()
  
  lastVideoId = currentVideoId
  
  if (message.language) {
    store.setSourceLanguage(message.language)
  }

  const { segments, isAutoGenerated } = SubtitleStore.parseYouTubeJSON(message.payload, config.autoGeneratedBatchSize)
  store.setIsAutoGenerated(isAutoGenerated)
  store.replaceSegments(segments)
}

// Exported for testing purposes
export const getLastVideoId = () => lastVideoId
export const setLastVideoId = (id: string | null) => { lastVideoId = id }
